<div class="hero-unit">
	<div class="row">
		<div class="col-lg-6 visible-lg">
			<img src="/gender.png" class="hero-image">
		</div>
		<div class="col-lg-6 col-sm-12">
			<h2>Send a letter</h2>
			Kogi retro ullamco, Williamsburg YOLO intelligentsia seitan DIY viral deserunt. Fanny pack tattooed cornhole, est accusamus semiotics asymmetrical 90's ethnic intelligentsia kogi.
			<br/><br/>
			<form>
    			<div class="hero-form col-12"><input type="text" id="form-name" class="form-control" placeholder="Name of organisation" /></div>
    			<div class="hero-form col-12"><input type="text" id="form-address" class="form-control" placeholder="Street Address" /></div>
    			<div class="hero-form col-6">
    				<input type="text" class="form-control" id="form-city" placeholder="City, town, etc" />
    			</div>
    			<div class="hero-form col-6">
    				<input type="text" class="form-control" id="form-postcode" placeholder="Postcode" />
    			</div>
    			<br/>
    			<button type="submit" class="btn btn-large btn-primary">Next...</button>
    		</form>
		</div>
	</div>
</div>